[workspace]
members = [
  "signatures",
  "signers_file",
  "aggregate_signature",
  "test_helpers",
  "common",
  "signers_file_types",
  "integration_tests",
  "user_lib",
]

[workspace.lints.clippy]
