[workspace]
members = [
  "core/signatures",
  "core/signers_file",
  "core/aggregate_signature",
  "core/test_helpers",
  "core/common",
  "core/signers_file_types",
  "core/integration_tests",
  "core/features_lib",
]

[workspace.lints.clippy]
