[package]
name = "test_helpers"
version = "0.1.0"
edition = "2024"

[dependencies]
signatures = { path = "../signatures" }
minisign = "0.8.0"
constants = { path = "../constants/" }
anyhow = "1.0.100"

[lints]
workspace = true
