[package]
name = "signers_file_types"
version = "0.1.0"
edition = "2024"

[dependencies]
minisign = "0.7.9"
common = { path = "../common/" }
signatures = { path = "../signatures/" }
serde = "1.0.226"
serde_json = "1.0.145"

[lints]
workspace = true
