[package]
name = "rest_api_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
uuid = { version = "1.19.0", features = ["v4"] }
features_lib = { path = "../core/features_lib/" }
signatures = { path = "../core/signatures/" }
thiserror = "2.0.17"

[lints]
workspace = true
